
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  name: 8att13-5nak35
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Self-Developed two player game on a single keyboard
  description: |
    Enjoy the war of space as you and your rival bet their snakes to eat the most among 10 bits of food and emerge as a Battle     Champion : Battle Snakes. You don't need to setup a wlan, lan or even have an internet access to play this small game.
  icon: https://github.com/HellBringer419/8att13-5nak35/blob/master/Resources/logo.png

  grade: stable
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    8att13-5nak35:
      command: java -jar $SNAP/BattleSnakes.jar

  parts:
    8att13-5nak35:
      # See 'snapcraft plugins'
      plugin: jdk
      source: https://github.com/HellBringer419/8att13-5nak35
      source-tag: 'v0.1'
      build: |
        export JAVA_HOME="usr/lib/jvm/java-8-openjdk-amd64"
      install: |
        unzip 8att13-5nak35.zip -d $SNAPCRAFT_PART_INSTALL/
      build-packages:
        - unzip
        - openjdk-8-jdk
